### ISSUE TITLE
No enum constant

### ISSUE THREAD

**Issue by hram** [jaredsburrows/gradle-spoon-plugin#16]
According to doc I can set test size small, medium or large
But if I set test size as 
`testSize = "small"`
I hav error

> No enum constant com.android.ddmlib.testrunner.IRemoteAndroidTestRunner.TestSize.small

Change paremeter to
`testSize = "SMALL"`
fixed this problem

**Comment by jaredsburrows** [comment]
Looks like we can add a test for this. Thanks for the find!

**Comment by jaredsburrows** [comment]
@hram I was able to repro this in a test:
```
com.jaredsburrows.spoon.SpoonTaskSpec > android - spoonFlavor2Flavor4DebugAndroidTest - full spoon extension - productFlavors - run task FAILED
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':spoonFlavor2Flavor4DebugAndroidTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.AbstractTask.execute(AbstractTask.java:384)
        at com.jaredsburrows.spoon.SpoonTaskSpec.android - #taskName - full spoon extension - productFlavors - run task(SpoonTaskSpec.groovy:226)

        Caused by:
        java.lang.IllegalArgumentException: No enum constant com.android.ddmlib.testrunner.IRemoteAndroidTestRunner.TestSize.large
            at java.lang.Enum.valueOf(Enum.java:238)
            at com.android.ddmlib.testrunner.IRemoteAndroidTestRunner$TestSize.valueOf(IRemoteAndroidTestRunner.java:32)
            at com.jaredsburrows.spoon.SpoonTask.spoonTask(SpoonTask.kt:95)
            at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
            ... 14 more

12 tests completed, 3 failed
```

**Comment by jaredsburrows** [comment]
@hram Please use the latest `1.4.0`.

**Comment by hram** [comment]
@jaredsburrows now its work

**Comment by jaredsburrows** [comment]
@hram Thanks for all the issues you have reported and thanks for updating.
