### ISSUE TITLE
Run annotated tests

### ISSUE THREAD

**Issue by hram** [jaredsburrows/gradle-spoon-plugin#9]
I was try to run annotated tests

> spoon {
    testSize = "large"
}

but build failed with error:

> Caused by: java.lang.IllegalArgumentException: No enum constant com.android.ddmlib.testrunner.IRemoteAndroidTestRunner.TestSize.large
        at com.android.ddmlib.testrunner.IRemoteAndroidTestRunner$TestSize.valueOf(IRemoteAndroidTestRunner.java:32)
        at com.jaredsburrows.spoon.SpoonTask.spoonTask(SpoonTask.kt:78)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)

**Comment by hram** [comment]
sorry my mistake
i anotated methods instead of classes
